language: c
compiler: gcc

os:
  - osx
  - linux

sudo: true

before_install:
  - if [ -z "${TRAVIS_OS_NAME}" ]; then export TRAVIS_OS_NAME=linux; fi;
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      travis_retry sudo apt-get update -qq;
      sudo apt-get install tree wget zsh tmux git curl -y;
    fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      travis_retry brew update;
      brew install tree;
      brew install wget;
      brew install zsh;
      brew install tmux;
      brew install git;
      brew install curl;
    fi

install:
  uname -a && export TRAVIS=true && export TEST=true && ./script/setup

script:
  uname -a && export TRAVIS=true && export TEST=true && ./script/test

notifications:
  email: false

# Local Variables:
# indent-tabs-mode: nil
# coding: utf-8
# End:
