# dotfiles: Docker Compose
# https://docs.docker.com/compose/
#
# Usage: docker-compose up
version: '3'
services:

  app:
    restart: always
    environment: &environment
      - APP_NAME=dotfiles
    build:
      context: .
      dockerfile: provision/docker/app/Dockerfile
      args:
        home: /usr/src
    volumes:
      - .:/usr/src/.dotfiles
    env_file:
      - .env

  docs:
    restart: always
    image: labpositiva/latex:3.6.1
    build:
      context: .
      dockerfile: provision/docker/docs/Dockerfile
    volumes:
      - .:/usr/src
    env_file:
      - .env
