version: '2'
services:
  dotfile:
    build: .
    image: luismayta/ubuntu-dotfiles:latest
    volumes_from:
      - source_store
    restart: always

  source_store:
    image: busybox
    volumes:
      - ./:/docker/.dotfiles
