---
name_inventory: local
path_inventory: provision/ansible/inventories/sandbox/local
vagrant:
  limit: 'all'
  verbose: 'vvvv'
  sudo: true

servers:
  - name: local.dotfiles.pe
    ip: 192.168.80.10
    box: ubuntu-14.4
    url: https://github.com/kraksoft/vagrant-box-ubuntu/releases/download/14.04/ubuntu-14.04-amd64.box
    hostname: local.dotfiles.pe
    ram: 512
