--- auto-import.lua
--- Recursively scans plugins/spec/ for spec files and generates plugins/init.lua
---
--- Usage: nvim --headless -c "lua vim.g.autoimport_output='$(dirname $0)/../lua/plugins/init.lua'" -c "luafile $(dirname $0)/auto-import.lua" -c "qa"

local OUTPUT
local SPEC_DIR
local OVERRIDE_DIR

--- Resolve base directories based on context.
--- When vim.g.autoimport_output is set (task build mode), derive from that path.
--- Otherwise use stdpath("config") for live config mode.
local function resolve_base_dirs()
  if vim.g.autoimport_output then
    OUTPUT = vim.g.autoimport_output
    -- From /path/to/data/lua/plugins/init.lua go up 1 dir to get /path/to/data/lua/plugins/
    local plugins_dir = vim.fn.fnamemodify(OUTPUT, ":h")
    SPEC_DIR = plugins_dir .. "/spec"
    OVERRIDE_DIR = plugins_dir .. "/override"
  else
    local config = vim.fn.stdpath("config")
    OUTPUT = config .. "/lua/plugins/init.lua"
    SPEC_DIR = config .. "/lua/plugins/spec"
    OVERRIDE_DIR = config .. "/lua/plugins/override"
  end
end

--- Recursively find all Lua files under a directory
---@param dir string
---@return string[] list of absolute paths
local function find_lua_files(dir)
  if vim.fn.isdirectory(dir) == 0 then
    return {}
  end
  local result = {}
  local function recurse(current)
    local entries = vim.fn.readdir(current)
    for _, entry in ipairs(entries) do
      local full = current .. "/" .. entry
      local stat = vim.fn.getftype(full)
      if stat == "dir" then
        recurse(full)
      elseif stat == "file" and entry:match("%.lua$") then
        table.insert(result, full)
      end
    end
  end
  recurse(dir)
  return result
end

--- Convert absolute spec path to lazy.nvim import string
--- e.g. /lua/plugins/spec/lang/python.lua -> plugins.spec.lang.python
---@param path string Absolute path
---@param base string Base directory path
---@return string import path
local function to_import_path(path, base)
  local relative = path:sub(#base + 2)
  relative = relative:gsub("%.lua$", "")
  relative = relative:gsub("/", ".")
  return relative
end

--- Validate that a spec file returns a table
---@param path string Absolute path to the spec file
---@return boolean ok, string|nil error
local function validate_spec(path)
  local fn, load_err = loadfile(path)
  local ok, result
  if fn then
    ok, result = pcall(fn)
  else
    ok, result = false, load_err
  end
  if not ok then
    return false, "Failed to load: " .. result
  end
  if type(result) ~= "table" then
    return false, "Does not return a table (got " .. type(result) .. ")"
  end
  return true, nil
end

--- Collect and validate spec files from a directory
---@param dir string Base directory
---@return table[] sorted list of { import = string, name = string }
local function collect_specs(dir)
  local files = find_lua_files(dir)
  local valid = {}

  for _, file in ipairs(files) do
    local ok, err = validate_spec(file)
    local import_base = vim.fn.fnamemodify(SPEC_DIR, ":h:h")
    local import_path = to_import_path(file, import_base)

    if ok then
      table.insert(valid, { import = import_path })
    else
      vim.notify("Skipping " .. file .. ": " .. err, vim.log.levels.WARN)
    end
  end

  table.sort(valid, function(a, b)
    return a.import:lower() < b.import:lower()
  end)

  return valid
end

--- Main: scan, validate, generate
local function main()
  resolve_base_dirs()
  local all_specs = collect_specs(SPEC_DIR)
  local all_overrides = collect_specs(OVERRIDE_DIR)

  if #all_specs == 0 and #all_overrides == 0 then
    vim.notify("No spec files found in: " .. SPEC_DIR, vim.log.levels.WARN)
    return
  end

  -- Generate output
  local lines = {
    "--- plugins/init.lua",
    "--- Auto-generated by auto-import.lua",
    '--- Do not edit manually; run "task build" to refresh',
    "---",
    "--- Generated: " .. os.date("%Y-%m-%d %H:%M:%S"),
    "",
    "return {",
  }

  -- Spec files (categorized by directory structure)
  for _, spec in ipairs(all_specs) do
    table.insert(lines, '  { import = "' .. spec.import .. '" },')
  end

  -- Override files (maintain order)
  if #all_overrides > 0 then
    table.insert(lines, "")
    table.insert(lines, "  -- Overrides")
    for _, spec in ipairs(all_overrides) do
      table.insert(lines, '  { import = "' .. spec.import .. '" },')
    end
  end

  table.insert(lines, "}")

  -- Write output
  vim.fn.writefile(lines, OUTPUT)
  vim.notify("Generated " .. OUTPUT .. " with " .. (#all_specs + #all_overrides) .. " specs", vim.log.levels.INFO)
end

main()
