require("core.extensions")
local hotkey = require('core.hotkey')
hotkey.bindWithCtrlAlt("a", "Load Atom", launchOrCycleFocus("Atom"))
hotkey.bindWithCtrlAlt("e", "Load Emacs", launchOrCycleFocus("Emacs"))
hotkey.bindWithCtrlAlt("c", "Load Calendar", launchOrCycleFocus("Calendar"))
hotkey.bindWithCtrlAlt("d", "Load Dash", launchOrCycleFocus("Dash"))
hotkey.bindWithCtrlAlt("t", "Load Alacritty", launchOrCycleFocus("Alacritty"))
hotkey.bindWithCtrlAlt("m", "Load Spotify", launchOrCycleFocus("Spotify"))
hotkey.bindWithCtrlAlt("x", "Load Xcode", launchOrCycleFocus("XCode"))
hotkey.bindWithCtrlAlt("i", "Load Insomnia", launchOrCycleFocus("Insomnia"))
hotkey.bindWithCtrlAlt("k", "Load Keybase", launchOrCycleFocus("Keybase"))
hotkey.bindWithCtrlAlt("o", "Load Finder", launchOrCycleFocus("Finder"))
hotkey.bindWithCtrlAlt("b", "Load Brave Browser", launchOrCycleFocus("Brave Browser"))
hotkey.bindWithCtrlAlt("r", "Load Reminders", launchOrCycleFocus("Reminders"))
hotkey.bindWithCtrlAlt("s", "Load Slack", launchOrCycleFocus("Slack"))
hotkey.bindWithCtrlAlt("`", "Load Open", function() os.execute( "open ~" ) end )
