#!/usr/bin/env bash

# Load the shell dotfiles, and then some:
# * ~/.extra can be used for other settings you don’t want to commit.
for file in ~/.{exports,bash_prompt,aliases,functions,inputrc}; do
	[ -r "$file" ] && source "$file"
done
unset file

eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"


[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

# Load Manager Version go Gvm
[[ -s "$HOME/.gvm/scripts/gvm" ]] && source "$HOME/.gvm/scripts/gvm"
