FROM labpositiva/latex:3.6.1
MAINTAINER Luis Mayta <@slovacus>

LABEL NAME latex
LABEL VERSION 3.6.1

# set working directory to /usr/src
WORKDIR /usr/src

# Install sphinx dependences
RUN pipenv install --dev