#!/usr/bin/env bash
# -*- coding: utf-8 -*-

[ -r "script/bootstrap.sh" ] && source "script/bootstrap.sh"

cat <<EOF

--------------------------
    Install
--------------------------

EOF

"$ROOT/install.sh"

cat <<EOF

--------------------------
    Finished Install
--------------------------

EOF

cat <<EOF

--------------------------
    Execution Boostrap
--------------------------

EOF

"$ROOT/bootstrap.sh"

cat <<EOF

--------------------------
    Finished Bootstrap
--------------------------

EOF