#!/usr/bin/env bash
# -*- coding: utf-8 -*-

ROOT="`pwd`"
HOME=~

[ -r "$ROOT/src/load.sh" ] && source "$ROOT/src/load.sh"

cat <<EOF

--------------------------
    Test Install
--------------------------

EOF

ret="0"
if [ ! -e "$HOME/.dotfiles/.git" ]; then
    ret="1"
    error "Error in Install"
else
    success "Yeah Install Done"
fi

cat <<EOF

--------------------------
    Test Bootstrap
--------------------------

EOF

for i in _ {a..z} {A..Z}; do
    for var in `eval echo "\\${!$i@}"`; do
        echo $var
        # you can test if $var matches some criteria and put it in the file or ignore
    done
done

for path in ${!PATH@}; do
    echo $path
    ret="0"
    if [[ ! -r $path ]]; then
        ret="1"
        error $path
    else
        success $path
    fi
done
unset path

cat <<EOF

--------------------------
    Test Executed
--------------------------

EOF

cat <<EOF

--------------------------
    Test Load Source
--------------------------

EOF

source "$HOME/.zshrc"