#!/usr/bin/env bash

ROOT="`pwd`"
HOME=~

[ -r "$ROOT/src/load.sh" ] && source "$ROOT/src/load.sh"

cat <<EOF

--------------------------
    Test Path
--------------------------

EOF

for path in "$HOME/".{pyenv,gvm,tmux,fonts,nvm,rvm}; do
    ret="0"
    if [[ ! -r $path ]]; then
        ret="1"
        error $path
    else
        success $path
    fi
done
unset path

cat <<EOF

--------------------------
    Test Executed
--------------------------

EOF
