---
version: "3"

tasks:
  readme:
    desc: Generate module README.md
    silent: true
    cmds:
      - >-
        gomplate --file {{.README_MODULE_TEMPLATE}}
        --out zsh/modules/nodejs/README.md
        --datasource config=zsh/modules/nodejs/README.yaml
        --datasource includes={{.README_INCLUDES}}

  sync:npmrc:
    desc: Sync npmrc config to home
    silent: true
    cmds:
      - nodejs::sync
