style: jira
template: CHANGELOG.tpl.md

info:
  title: CHANGELOG
  repository_url: https://github.com/luismayta/dotfiles
options:
  commits:
    filters:
      Type:
        - chore
        - refactor
        - feat
        - fix
        - hotfix
        - perf
        - deprecate
        - revert
        - docs
    sort_by: Scope

  commit_groups:
    group_by: Scope
    sort_by: Title
    title_order:
      - chore
      - refactor
      - feat
      - fix
      - hotfix
      - perf
      - deprecate
      - revert
      - docs
    title_maps:
      refactor: 🎨 Code Refactoring
      feat: ✨ Features
      fix: 🐛 Bug Fixes
      hotfix: 🚑 Hotfixes
      perf: ⚡ Performance Improvements
      deprecate: ⚰ Deprecations
      revert: ⏪ Reverts
      docs: 📚 Documentation

  header:
    pattern: "^(\\w+)(?:\\s*[^(:]*)?(?:\\s*\\((.*?)\\))?:\\s*(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject

  merges:
    pattern: "^Merge branch '(\\w+)'$"
    pattern_maps:
      - Source

  reverts:
    pattern: "^Revert \"([\\s\\S]*)\"$"
    pattern_maps:
      - Header

  notes:
    keywords:
      - BREAKING CHANGE
      - 💥
