#!/usr/bin/env bash
# -*- coding: utf-8 -*-

export TERM=xterm-256color
export GO_ENV="$HOME/.goenvs"

export PROJECTS="$HOME/projects"

export DISABLE_AUTO_TITLE="true"

[[ -e "$HOME/.wakatime" ]] && export PATH_WAKATIME="$HOME/.wakatime"

# Make vim the default editor
[[ -e "/usr/bin/vim" ]] && export EDITOR=/usr/bin/vim

# Larger bash history (allow 32³ entries; default is 500)

export HISTFILE="$HOME/.zsh_history"
export HISTSIZE=100000
export HISTCONTROL=ignoredups
export SAVEHIST=$HISTSIZE

# Prefer US English and use UTF-8
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# PATHS APPLICATIONS

# Add `~/bin` to the `$PATH`
[[ -e "$HOME/bin" ]] && export PATH="$PATH:$HOME/bin"

# Add var plantuml.jar
export PLANTUML_JAR_PATH="$HOME/.dotfiles/extras/jar/plantuml.jar"
