#!/usr/bin/env bash

export PATH="$HOME/.pyenv/bin:$PATH"
export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
# Add `~/bin` to the `$PATH`
export PATH="$HOME/bin:$PATH"

# Make vim the default editor
export EDITOR=/usr/bin/vim

# Larger bash history (allow 32³ entries; default is 500)
export HISTSIZE=32768
export HISTFILESIZE=$HISTSIZE
export HISTCONTROL=ignoredups
# Make some commands not show up in history
#export HISTIGNORE="ls:cd:cd -:pwd:exit:date:* --help"

# Prefer US English and use UTF-8
export LANG=en_US.UTF-8
export LC_ALL="en_US.UTF-8"

# Highlight section titles in manual pages
#export LESS_TERMCAP_md="$ORANGE"

# Don’t clear the screen after quitting a manual page
#export MANPAGER="less -X"

# Always enable colored `grep` output
#export GREP_OPTIONS="--color=auto"

# Link Homebrew casks in `/Applications` rather than `~/Applications`

#export HOMEBREW_CASK_OPTS="--appdir=/Applications"
export TERM=screen-256color-bce
