#!/usr/bin/env bash
# -*- coding: utf-8 -*-
export TERM='xterm-256color'
export GO_ENV=~/.goenvs

export PROJECTS=~/projects

export DISABLE_AUTO_TITLE="true"

# Make vim the default editor
export EDITOR=/usr/bin/vim

# Larger bash history (allow 32³ entries; default is 500)
export HISTFILE=~/.zsh_history
export HISTSIZE=100000
export HISTCONTROL=ignoredups
export SAVEHIST=$HISTSIZE

# Prefer US English and use UTF-8
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

export NVM_DIR="$HOME/.nvm"

export TERM='xterm-256color'
