#!/usr/bin/env bash
# -*- coding: utf-8 -*-

# Load the shell dotfiles, and then some:
# * ~/.customrc can be used for other settings you don’t want to commit.
# shellcheck source=/dev/null
for file in ~/.{aliases,customrc}; do
  [ -r "${file}" ] && source "${file}"
done
unset file
