#!/usr/bin/env bash
# -*- coding: utf-8 -*-

# Load the shell dotfiles, and then some:
# * ~/.extra can be used for other settings you don’t want to commit.
for file in ~/.{exports,bash_prompt,load,aliases,functions,inputrc,customrc}; do
	[ -r "$file" ] && source "$file"
done
unset file
