#!/usr/bin/env zsh
# -*- coding: utf-8 -*-

export ZSH=$HOME/.dotfiles

# AUTO-UPDATES
export UPDATE_ZSH_DAYS=1

# DISABLE AUTOCORRECTION
DISABLE_CORRECTION="true"

# ANTIGEN — plugin manager
source ~/.antibody/antibody.zsh

# setup antibody
antibody bundle < "$ZSH/tools/antibody/bundles.txt"

# load everything but the path and completion files
source "$ZSH/zsh/completion.zsh"

# initialize autocomplete here, otherwise functions won't be loaded
autoload -U compinit
compinit -i -d ${ZSH_COMPDUMP}

# source "$ZSH/zsh/completion.zsh"

# Add `~/bin` to the `$PATH`
[[ -e "$HOME/bin" ]] && export PATH="$PATH:$HOME/bin"

# Add Pyenv to Path scripting
[[ -e "$HOME/.pyenv/bin" ]] && export PATH="$PATH:$HOME/.pyenv/bin"

# Add RVM to PATH for scripting
[[ -e "$HOME/.rvm/bin" ]] && export PATH="$PATH:$HOME/.rvm/bin"

# Add NVM to Path for scripting
[[ -e "$HOME/.nvm" ]] && export NVM_DIR="$HOME/nvm"

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

# Load Manager Version go Gvm
[[ -s "$HOME/.gvm/scripts/gvm" ]] && source "$HOME/.gvm/scripts/gvm"

if [ -e "$HOME/.pyenv" ]; then
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"
fi

[ -r ~/.bashrc ] && source ~/.bashrc
