#!/usr/bin/env ksh
# -*- coding: utf-8 -*-

if [ -n "${ZSH_DEBUG}" ]; then
    zmodload zsh/zprof
fi

export ZSH_TMUX_AUTOSTART=false

export ZSH=${HOME}/.dotfiles
export DOTFILES="${HOME}/.dotfiles"
export DOTFILES_DIR="${DOTFILES}/src"
export DOTFILES_BIN="${DOTFILES}/bin"
export MOD_DIR="${DOTFILES_DIR}/zsh/mod"
export PRIVATERC="${HOME}/.privaterc"
export CUSTOMRC="${HOME}/.customrc"
export PROFILERC="${HOME}/.profile"

export PATH="${DOTFILES_BIN}:${PATH}"

# language
export LANG="en_US.UTF-8"
export LC_ALL=$LANG

[ -e "${HOME}/.local/bin" ] && export PATH="${HOME}/.local/bin:${PATH}"
[ -e "${HOME}/local/bin" ] && export PATH="${HOME}/local/bin:${PATH}"
[ -e "/usr/local/sbin" ] && export PATH="/usr/local/sbin:${PATH}"
[ -e "/usr/local/opt/qt/bin" ] && export PATH="/usr/local/opt/qt/bin:${PATH}"

[ -e "/usr/local/bin/zsh" ] && export SHELL=/usr/local/bin/zsh
[ -e "/usr/bin/zsh" ] && export SHELL=/usr/bin/zsh

# Make vim the default editor
if type -p vim > /dev/null; then
    export EDITOR=vim
fi

# Make nvim the default editor
if type -p nvim > /dev/null; then
    export EDITOR=nvim
fi

export GIT_INTERNAL_GETTEXT_TEST_FALLBACKS=1

# shellcheck source=/dev/null
[ -e "${MOD_DIR}/zsh.zsh" ] && source "${MOD_DIR}/zsh.zsh"

# shellcheck source=/dev/null
[ -e "${MOD_DIR}/completions.zsh" ] && source "${MOD_DIR}/completions.zsh"

# shellcheck source=/dev/null
[ -e "${MOD_DIR}/vim.zsh" ] && source "${MOD_DIR}/vim.zsh"

# ANTIBODY — plugin manager

# shellcheck source=/dev/null
source <(antibody init)

# setup antibody
antibody bundle zsh-users/zsh-syntax-highlighting
antibody bundle caarlos0/zsh-git-sync
antibody bundle mafredri/zsh-async
antibody bundle willghatch/zsh-hooks
antibody bundle agkozak/zhooks
antibody bundle unixorn/git-extra-commands
antibody bundle luismayta/zsh-functions branch:develop
antibody bundle Aloxaf/fzf-tab
antibody bundle luismayta/zsh-brew branch:develop
antibody bundle luismayta/zsh-aliases branch:develop
antibody bundle luismayta/zsh-git-aliases branch:develop
antibody bundle luismayta/zsh-deno branch:develop
antibody bundle luismayta/zsh-alacritty branch:develop
antibody bundle luismayta/zsh-keybase branch:develop
antibody bundle equipindustry/zsh-templates branch:develop
antibody bundle luismayta/zsh-docker branch:develop
antibody bundle luismayta/zsh-docker-aliases branch:develop
antibody bundle luismayta/zsh-docker-compose-aliases branch:develop
antibody bundle luismayta/zsh-pyenv branch:develop
antibody bundle luismayta/zsh-pipenv branch:develop
antibody bundle luismayta/zsh-tfenv branch:develop
antibody bundle equipindustry/zsh-goenv branch:develop
antibody bundle equipindustry/zsh-nvm branch:develop
antibody bundle luismayta/zsh-yarn branch:develop
antibody bundle luismayta/zsh-rvm branch:develop
antibody bundle luismayta/zsh-rust branch:develop
antibody bundle luismayta/zsh-resources branch:develop
antibody bundle luismayta/zsh-servers-functions branch:develop
antibody bundle luismayta/zsh-ssh-connect branch:develop
antibody bundle luismayta/zsh-vscode branch:develop
antibody bundle luismayta/zsh-issues branch:develop
antibody bundle equipindustry/zsh-ghq branch:develop
antibody bundle luismayta/zsh-gst branch:develop
antibody bundle luismayta/zsh-trash branch:develop
antibody bundle luismayta/zsh-transfer branch:develop
antibody bundle luismayta/zsh-pazi branch:develop
antibody bundle luismayta/zsh-flutter branch:develop
antibody bundle luismayta/zsh-clean branch:develop
antibody bundle luismayta/zsh-bitwarden branch:develop
antibody bundle chrissicool/zsh-256color
antibody bundle wbinglee/zsh-wakatime
antibody bundle zsh-users/zsh-completions
antibody bundle zdharma/fast-syntax-highlighting
antibody bundle zsh-users/zsh-autosuggestions
antibody bundle zsh-users/zsh-history-substring-search
antibody bundle sindresorhus/pretty-time-zsh
antibody bundle luismayta/zsh-history branch:develop
antibody bundle luismayta/zsh-starship branch:develop
antibody bundle luismayta/zsh-notify branch:develop
antibody bundle luismayta/zsh-tmux branch:develop
antibody bundle luismayta/zsh-restic branch:develop
antibody bundle luismayta/zsh-osx branch:develop
antibody bundle luismayta/zsh-scmbreeze branch:develop
antibody bundle luismayta/zsh-aws branch:develop
antibody bundle luismayta/zsh-apps branch:develop

# Keybindings
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
bindkey '^[[3~' delete-char
bindkey '^[3;5~' delete-char

[ -z "${TMUX}" ] && tmux new-session -A -s "${USER}"

# shellcheck source=/dev/null
[ -f "${PROFILERC}" ] && source "${PROFILERC}"

if [ -n "${GITHUB_TOKEN}" ]; then
    git config --global \
        url."https://${GITHUB_TOKEN}:@github.com/".insteadOf "https://github.com/"
fi

# shellcheck source=/dev/null
[ -f "${PRIVATERC}" ] && source "${PRIVATERC}"

# remove duplicates path
if ! type -p path_remove_duplicate > /dev/null; then
    path_remove_duplicate
fi
