#!/usr/bin/env zsh
# -*- coding: utf-8 -*-

#zmodload zsh/zprof

export ZSH=$HOME/.dotfiles
export DOTFILES="$HOME/.dotfiles"

export SHELL=/bin/zsh


# DISABLE AUTOCORRECTION
DISABLE_CORRECTION="true"

# autoload color
autoload -U colors && colors

# ANTIBODY — plugin manager
source <(antibody init)

# setup antibody
antibody bundle caarlos0/zsh-git-sync
antibody bundle mafredri/zsh-async
antibody bundle willghatch/zsh-hooks
antibody bundle luismayta/zsh-functions branch:develop
antibody bundle unixorn/git-extra-commands
antibody bundle luismayta/zsh-brew branch:develop
antibody bundle luismayta/zsh-aliases branch:develop
antibody bundle luismayta/zsh-git-aliases
antibody bundle luismayta/zsh-docker-aliases
antibody bundle luismayta/zsh-docker-compose-aliases
antibody bundle luismayta/zsh-servers-functions
antibody bundle luismayta/zsh-ssh-connect branch:develop
antibody bundle luismayta/zsh-goenv branch:develop
antibody bundle luismayta/zsh-nvm branch:develop
antibody bundle luismayta/zsh-rvm branch:develop
antibody bundle luismayta/zsh-rust branch:develop
antibody bundle luismayta/zsh-vscode branch:develop
antibody bundle luismayta/zsh-pyenv branch:develop
antibody bundle luismayta/zsh-pipenv branch:develop
antibody bundle luismayta/zsh-tfenv branch:develop
antibody bundle luismayta/zsh-ghq branch:develop
antibody bundle luismayta/zsh-trash branch:develop
antibody bundle luismayta/zsh-transfer branch:develop
antibody bundle luismayta/zsh-pazi branch:develop
antibody bundle luismayta/zsh-flutter branch:develop
antibody bundle luismayta/zsh-clean branch:develop
antibody bundle luismayta/zsh-bitwarden branch:develop
antibody bundle chrissicool/zsh-256color
antibody bundle wbinglee/zsh-wakatime
antibody bundle zsh-users/zsh-completions
antibody bundle zdharma/fast-syntax-highlighting
antibody bundle zsh-users/zsh-autosuggestions
antibody bundle zsh-users/zsh-history-substring-search
#antibody bundle zsh-users/zsh-syntax-highlighting
antibody bundle b4b4r07/zsh-vimode-visual
antibody bundle sindresorhus/pretty-time-zsh
#antibody bundle luismayta/zsh-history branch:develop
antibody bundle sindresorhus/pure
antibody bundle piger/zsh-notify
antibody bundle luismayta/zsh-tmux
antibody bundle luismayta/zsh-restic
antibody bundle luismayta/zsh-osx

#nodejs
antibody bundle buonomo/yarn-completion

# load everything but the path and completion files
source "$ZSH/zsh/completions.zsh"

# Keybindings
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
bindkey '^[[3~' delete-char
bindkey '^[3;5~' delete-char

# initialize autocomplete here, otherwise functions won't be loaded
autoload -U compinit
compinit -i -d ${ZSH_COMPDUMP}

# don't put duplicate lines in the history. See bash(1) for more options
# ... or force ignoredups and ignorespace
HISTCONTROL=ignoredups:ignorespace

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

alias reload!='exec "$SHELL" -l'

ZSH_TMUX_AUTOSTART=false
[[ $TMUX == "" ]] && tmux new-session -A -s "${USER}"

# shellcheck source=/dev/null
[ -f "$HOME/.profile" ] && source "$HOME/.profile"
