# shellcheck shell=bash
# macOS-specific herdr configuration
export ZSH_HERDR_CLIPBOARD_COPY_CMD="${ZSH_HERDR_CLIPBOARD_COPY_CMD:-pbcopy}"
export ZSH_HERDR_CLIPBOARD_PASTE_CMD="${ZSH_HERDR_CLIPBOARD_PASTE_CMD:-pbpaste}"

# Backward-compatible aliases
export HERDR_CLIPBOARD_COPY_CMD="${ZSH_HERDR_CLIPBOARD_COPY_CMD}"
export HERDR_CLIPBOARD_PASTE_CMD="${ZSH_HERDR_CLIPBOARD_PASTE_CMD}"
