# autoload
autoload -Uz add-zsh-hook
autoload -Uz compinit && compinit -u

export GIT_INTERNAL_GETTEXT_TEST_FALLBACKS=1

export TERM=xterm-256color
if [ -z "${PROJECTS}" ]; then
    export PROJECTS="${HOME}/Projects/src"
    mkdir -p "${PROJECTS}"
fi

export DISABLE_AUTO_TITLE="true"

if ! type -p wakatime > /dev/null; then
    [ -e "${HOME}/.wakatime" ] && export PATH_WAKATIME="${HOME}/.wakatime"
fi

# Make vim the default editor
if type -p vim > /dev/null; then
    export EDITOR=vim
fi

# Make nvim the default editor
if type -p nvim > /dev/null; then
    export EDITOR=nvim
fi

# Larger bash history (allow 32³ entries; default is 500)

export HISTFILE="${HOME}/.zsh_history"
export HISTSIZE=100000
export HISTCONTROL=ignoredups
export SAVEHIST="${HISTSIZE}"

# Prefer US English and use UTF-8
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

if ! type -p pyenv > /dev/null; then
    [ -e "${HOME}/.pyenv" ] && export PYENV_ROOT="${HOME}/.pyenv"
    [ -e "${HOME}/.pyenv/bin" ] && export PATH="${PATH}:${HOME}/.pyenv/bin"
    export PIPENV_PYTHON="${PYENV_ROOT}/shims/python"
    export PYENV_VIRTUALENV_DISABLE_PROMPT=1
fi

export PIPENV_SHELL_FANCY=true

# Prefer US English and use UTF-8
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

if ! type -p pyenv > /dev/null; then
    [ -e "${HOME}/.pyenv" ] && export PYENV_ROOT="${HOME}/.pyenv"
    [ -e "${HOME}/.pyenv/bin" ] && export PATH="${PATH}:${HOME}/.pyenv/bin"
    export PIPENV_PYTHON="${PYENV_ROOT}/shims/python"
    export PYENV_VIRTUALENV_DISABLE_PROMPT=1
fi

[ -e "${HOME}/.goenv/bin" ] && export PATH="${PATH}:${HOME}/.goenv/bin"
[ -e "${HOME}/.docker-slim/bin" ] && export PATH="${PATH}:${HOME}/.docker-slim/bin"
