# autoload
autoload -Uz add-zsh-hook
autoload -Uz compinit && compinit -u

export GIT_INTERNAL_GETTEXT_TEST_FALLBACKS=1

export TERM=screen-256color

if [ -z "${PROJECTS}" ]; then
    export PROJECTS="${HOME}/Projects/src"
    mkdir -p "${PROJECTS}"
fi

export DISABLE_AUTO_TITLE="true"

if ! type -p wakatime > /dev/null; then
    [ -e "${HOME}/.wakatime" ] && export PATH_WAKATIME="${HOME}/.wakatime"
fi

# Larger bash history (allow 32³ entries; default is 500)

export HISTFILE="${HOME}/.zsh_history"
export HISTSIZE=100000
export HISTCONTROL=ignoredups
export SAVEHIST="${HISTSIZE}"

# Prefer US English and use UTF-8
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

export PIPENV_SHELL_FANCY=true

if ! type -p pyenv > /dev/null; then
    [ -e "${HOME}/.pyenv" ] && export PYENV_ROOT="${HOME}/.pyenv"
    [ -e "${HOME}/.pyenv/bin" ] && export PATH="${PATH}:${HOME}/.pyenv/bin"
fi

if type -p pyenv > /dev/null; then
    export PIPENV_PYTHON="${PYENV_ROOT}/shims/python"
    export PYENV_VIRTUALENV_DISABLE_PROMPT=1
fi

if [ -d "/home/linuxbrew/.linuxbrew/bin" ]; then
    export PATH="/home/linuxbrew/.linuxbrew/bin:${PATH}"
fi

if [ -d "${HOME}/.linuxbrew/bin" ]; then
    export PATH="${HOME}/.linuxbrew/bin:${PATH}"
fi

. "$HOME/.cargo/env"
