# Add zsh functions to fpath for autoload
if [[ -d "/opt/homebrew/share/zsh/functions" ]]; then
  # macOS (Homebrew)
  fpath=(/opt/homebrew/share/zsh/functions $fpath)
elif [[ -d "/usr/share/zsh/5.9/functions" ]]; then
  # Linux (system zsh)
  fpath=(/usr/share/zsh/5.9/functions $fpath)
elif [[ -d "/usr/share/zsh/functions" ]]; then
  # Linux (alternative path)
  fpath=(/usr/share/zsh/functions $fpath)
fi

# autoload
autoload -Uz add-zsh-hook
autoload -Uz compinit && compinit -u

export GIT_INTERNAL_GETTEXT_TEST_FALLBACKS=1

export TERM=screen-256color

if [ -z "${PROJECTS}" ]; then
    export PROJECTS="${HOME}/Projects/src"
    mkdir -p "${PROJECTS}"
fi

export DISABLE_AUTO_TITLE="true"

if ! type -p wakatime > /dev/null; then
    [ -e "${HOME}/.wakatime" ] && export PATH_WAKATIME="${HOME}/.wakatime"
fi

# Larger bash history (allow 32³ entries; default is 500)

export HISTFILE="${HOME}/.zsh_history"
export HISTSIZE=100000
export HISTCONTROL=ignoredups
export SAVEHIST="${HISTSIZE}"

# Prefer US English and use UTF-8
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

export PIPENV_SHELL_FANCY=true

. "$HOME/.cargo/env"

if [ -e "$HOME/.nix-profile/etc/profile.d/nix.sh" ]; then . "$HOME/.nix-profile/etc/profile.d/nix.sh"; fi # added by Nix installer
if [ -d "$HOME/.local/bin" ]; then export PATH="$HOME/.local/bin:$PATH"; fi # uv (astral.sh installer)
