---
version: "3"

tasks:
  readme:
    desc: Generate module README.md
    silent: true
    cmds:
      - >-
        gomplate --file {{.README_MODULE_TEMPLATE}}
        --out zsh/modules/tmux/README.md
        --datasource config=zsh/modules/tmux/README.yaml
        --datasource includes={{.README_INCLUDES}}
