# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: dotfiles
env:
  - GO111MODULE=on
  - REPO=github.com/luismayta/dotfiles
before:
  hooks:
    - go mod download
    - go mod tidy
    - go mod vendor
    - go generate ./...

# https://goreleaser.com/build/
builds:
  # Defaults to the project name.
  - id: default
    # ID of the build.
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X "{{.Env.REPO}}/cmd.Version={{.Version}}"
      - -X "{{.Env.REPO}}/cmd.Commit={{.FullCommit}}"
      - -X "{{.Env.REPO}}/cmd.RepoURL={{.GitURL}}"
      - -X "{{.Env.REPO}}/cmd.BuildDate={{.Date}}"
      - -X "{{.Env.REPO}}/cmd.BuiltWithGoVersion={{.Env.GO_VERSION}}"
      - -X "{{.Env.REPO}}/cmd.BuiltBy={{.Env.BUILT_BY}}"
    goos:
      - darwin
      - linux
    goarch:
      - amd64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
    builds:
      - default
    wrap_in_directory: true
    name_template: '{{.ProjectName}}-{{.Os}}-{{.Arch}}'
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
      - config/**/*
      - systemd/*
# https://goreleaser.com/snapshots/
snapshot:
  name_template: 'dev@{{.ShortCommit}}'

# https://goreleaser.com/checksum/
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
  algorithm: sha256
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  github:
    owner: hadenlabs
    name: dotfiles
  draft: true
  prerelease: auto
  name_template: '{{.ProjectName}}-v{{.Version}}-{{.ShortCommit}}-{{.Date}}'
