# Docker Compose
# https://docs.docker.com/compose/
# Usage: docker-compose up
---
version: "3.6"
services:

  app:
    environment: &environment
      - APP_NAME=dotfiles
    build:
      context: .
      dockerfile: provision/docker/app/Dockerfile
