# Docker Compose
# https://docs.docker.com/compose/
#
# Usage: test up

services:
  app:
    image: dotfiles-app-test
    environment: &environment
      - APP_NAME=dotfiles
    build:
      args:
        stage: test

  docs:
    restart: always
    build:
      context: .
      dockerfile: provision/docker/docs/Dockerfile
    volumes:
      - .:/usr/src
    env_file:
      - .env
