# Docker Compose
# https://docs.docker.com/compose/

version: '3'
services:

  app:
    environment: &environment
      - APP_NAME=dotfiles
    build:
      context: .
      dockerfile: provision/docker/app-test/Dockerfile
      args:
        stage: test
