# Docker Compose
# https://docs.docker.com/compose/
#
# Usage: test up

services:
  app:
    image: dotfiles-app-test
    environment: &environment
      - APP_NAME=dotfiles
    build:
      args:
        stage: test
