#!/usr/bin/env ksh
# -*- coding: utf-8 -*-

# ---------------------------------------------------------------------------
# Linux-specific cleanup paths
# Organized by function category — system, package managers, development, user
# ---------------------------------------------------------------------------

# ── System: Trash ──────────────────────────────────────────────────────────
# Trash files via FreeDesktop Trash specification
export CLEAN_LINUX_TRASH_FILES="${HOME}/.local/share/Trash/files"

# Trash metadata (dates, original paths)
export CLEAN_LINUX_TRASH_INFO="${HOME}/.local/share/Trash/info"

# ── System: Logs ───────────────────────────────────────────────────────────
# System log files in /var/log
export CLEAN_LINUX_LOG_VAR="/var/log"

# Nested system logs (per-service directories)
export CLEAN_LINUX_LOG_SUBDIR="/var/log"

# Temporary files
export CLEAN_LINUX_TMP="/tmp"

# ── System: Journal / Service Caches ───────────────────────────────────────
# Per-user systemd journal cache
export CLEAN_LINUX_JOURNAL_CACHE="${HOME}/.cache/journal"

# Systemd core dumps
export CLEAN_LINUX_COREDUMP="${HOME}/.local/share/systemd/coredump"

# ── Package Manager: npm ──────────────────────────────────────────────────
# npm cache directory (package tarballs and metadata)
export CLEAN_LINUX_NPM_CACHE="${HOME}/.npm/_cacache"

# ── Package Manager: yarn ─────────────────────────────────────────────────
# Yarn cache (Offline mirror of downloaded packages)
export CLEAN_LINUX_YARN_CACHE="${HOME}/.cache/yarn"

# ── Package Manager: pip ──────────────────────────────────────────────────
# pip cache directory (downloaded wheels and build artifacts)
export CLEAN_LINUX_PIP_CACHE="${HOME}/.cache/pip"

# ── Package Manager: cargo/rust ──────────────────────────────────────────
# Cargo registry cache (downloaded crate archives)
export CLEAN_LINUX_CARGO_REGISTRY="${HOME}/.cargo/registry/cache"

# Cargo installed binaries (can be rebuilt from source)
export CLEAN_LINUX_CARGO_BIN="${HOME}/.cargo/bin"

# ── Package Manager: go ───────────────────────────────────────────────────
# Go module download cache
export CLEAN_LINUX_GO_MODCACHE="${HOME}/go/pkg/mod/cache"

# ── Development: Pre-commit ───────────────────────────────────────────────
# Pre-commit hook cache (repositories and environments)
export CLEAN_LINUX_PRECOMMIT_CACHE="${HOME}/.cache/pre-commit"

# ── Development: ccache ──────────────────────────────────────────────────
# C/C++ compiler cache artifacts
export CLEAN_LINUX_CCACHE="${HOME}/.ccache"

# ── Development: pytest / mypy ───────────────────────────────────────────
# pytest cache (previous test results and fixtures)
export CLEAN_LINUX_PYTEST_CACHE="${HOME}/.cache/pytest"

# mypy cache (type-checking bytecode cache)
export CLEAN_LINUX_MYPY_CACHE="${HOME}/.cache/mypy"

# ── User Data: Thumbnails ─────────────────────────────────────────────────
# Freedesktop thumbnail cache (regenerated by file manager on demand)
export CLEAN_LINUX_THUMBNAILS="${HOME}/.cache/thumbnails"

# ── User Data: Browser Caches ─────────────────────────────────────────────
# Google Chrome browser cache
export CLEAN_LINUX_CHROME_CACHE="${HOME}/.cache/google-chrome"

# Firefox browser cache
export CLEAN_LINUX_FIREFOX_CACHE="${HOME}/.cache/firefox"
